language:
  - node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/reg_numbers_test

before_script:
  - psql -c 'create database reg_numbers_test;' -U postgres
  - psql -U postgres -d reg_numbers_test -a -f database.sql

services:
  - postgresql
