language:
  - node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeted_test

before_script:
  - psql -c 'create database greeted_test;' -U postgres
  - psql -U postgres -d greeted_test -a -f database.sql

services:
  - postgresql
